name: Run test suite

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ubuntu-latest]
    environment: release  # has the secrets defined

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android build-tools
        # See versions at
        # https://developer.android.com/tools/releases/build-tools
        run: |
          $ANDROID_HOME/cmdline-tools/16.0/bin/sdkmanager "build-tools;34.0.0"
          echo "$ANDROID_HOME/build-tools/34.0.0" >> "$GITHUB_PATH"

      - name: Make gradlew executable
        # required to run ./gradlew commands
        run: chmod +x gradlew

      - name: Run Tests
        run: |
          ./gradlew --no-daemon --warning-mode all test
